### Import your libraries

In [44]:
from google.colab import drive
drive.mount('/content/drive')

%cd /content/drive/MyDrive

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content/drive/MyDrive

In [45]:
import pandas as pd

### Load your dataset

In [46]:
df = pd.read_csv("HR_Missing_Vslues.csv")

In [47]:
df.head()

,Employee_Name,EmpID,Salary,PositionID,Position,DOB,Sex,MaritalDesc,RaceDesc,DateofHire,DateofTermination,Department,ManagerName,ManagerID,RecruitmentSource,Absences
0,"Adinolfi, Wilson K",10026,62506.0,19,Production Technician I,07/10/83,M,Single,White,7/5/2011,NaN,Production,Michael Albert,22.0,LinkedIn,1.0
1,"Ait Sidi, Karthikeyan",10084,104437.0,27,Sr. DBA,05/05/75,M,Married,White,3/30/2015,6/16/2016,IT/IS,Simon Roup,4.0,Indeed,17.0
2,"Akinkuolie, Sarah",10196,64955.0,20,Production Technician II,09/19/88,F,Married,White,7/5/2011,9/24/2012,Production,Kissy Sullivan,20.0,LinkedIn,3.0
3,"Alagbe,Trina",10088,64991.0,19,Production Technician I,NaN,F,Married,White,1/7/2008,NaN,Production,Elijiah Gray,16.0,Indeed,15.0
4,NaN,10069,50825.0,19,Production Technician I,09/08/89,F,Divorced,White,7/11/2011,9/6/2016,Production,Webster Butler,39.0,Google Search,2.0

### Explore your data

* First 5 recods
* Last 5 records
* Check data type
* Show statistical summary
* Is there any missing values ?
* Applay two more data analysis from your choose

In [48]:
# First 5 records
df.head(5)

,Employee_Name,EmpID,Salary,PositionID,Position,DOB,Sex,MaritalDesc,RaceDesc,DateofHire,DateofTermination,Department,ManagerName,ManagerID,RecruitmentSource,Absences
0,"Adinolfi, Wilson K",10026,62506.0,19,Production Technician I,07/10/83,M,Single,White,7/5/2011,NaN,Production,Michael Albert,22.0,LinkedIn,1.0
1,"Ait Sidi, Karthikeyan",10084,104437.0,27,Sr. DBA,05/05/75,M,Married,White,3/30/2015,6/16/2016,IT/IS,Simon Roup,4.0,Indeed,17.0
2,"Akinkuolie, Sarah",10196,64955.0,20,Production Technician II,09/19/88,F,Married,White,7/5/2011,9/24/2012,Production,Kissy Sullivan,20.0,LinkedIn,3.0
3,"Alagbe,Trina",10088,64991.0,19,Production Technician I,NaN,F,Married,White,1/7/2008,NaN,Production,Elijiah Gray,16.0,Indeed,15.0
4,NaN,10069,50825.0,19,Production Technician I,09/08/89,F,Divorced,White,7/11/2011,9/6/2016,Production,Webster Butler,39.0,Google Search,2.0

In [49]:
# Last 5 records
df.tail(5)

,Employee_Name,EmpID,Salary,PositionID,Position,DOB,Sex,MaritalDesc,RaceDesc,DateofHire,DateofTermination,Department,ManagerName,ManagerID,RecruitmentSource,Absences
306,"Woodson, Jason",10135,65893.0,20,Production Technician II,05/11/85,M,Single,White,7/7/2014,NaN,Production,Kissy Sullivan,20.0,LinkedIn,13.0
307,"Ybarra, Catherine",10301,48513.0,19,Production Technician I,NaN,F,Single,Asian,9/2/2008,9/29/2015,Production,Brannon Miller,12.0,Google Search,4.0
308,NaN,10010,220450.0,6,CIO,NaN,F,Single,White,4/10/2010,NaN,IT/IS,Janet King,2.0,Employee Referral,16.0
309,"Zhou, Julia",10043,89292.0,9,Data Analyst,02/24/79,F,Single,White,3/30/2015,NaN,IT/IS,Simon Roup,4.0,Employee Referral,NaN
310,NaN,10271,45046.0,19,Production Technician I,08/17/78,F,Widowed,Asian,9/29/2014,NaN,Production,David Stanley,14.0,LinkedIn,2.0

In [50]:
# Check data types
df.dtypes

Employee_Name         object
EmpID                  int64
Salary               float64
PositionID             int64
Position              object
DOB                   object
Sex                   object
MaritalDesc           object
RaceDesc              object
DateofHire            object
DateofTermination     object
Department            object
ManagerName           object
ManagerID            float64
RecruitmentSource     object
Absences             float64
dtype: object

In [51]:
# Statistical summary
df.describe()

              EmpID         Salary  PositionID   ManagerID    Absences
count    311.000000     249.000000  311.000000  303.000000  280.000000
mean   10156.000000   67972.662651   16.845659   14.570957   10.128571
std       89.922189   22995.908395    6.223419    8.078306    5.946407
min    10001.000000   45046.000000    1.000000    1.000000    1.000000
25%    10078.500000   55315.000000   18.000000   10.000000    4.750000
50%    10156.000000   62957.000000   19.000000   15.000000   10.000000
75%    10233.500000   71707.000000   20.000000   19.000000   15.250000
max    10311.000000  220450.000000   30.000000   39.000000   20.000000

In [52]:
# Check for missing values
df.isnull().sum()

Employee_Name         93
EmpID                  0
Salary                62
PositionID             0
Position               0
DOB                   31
Sex                   62
MaritalDesc            0
RaceDesc               0
DateofHire             0
DateofTermination    207
Department             0
ManagerName            0
ManagerID              8
RecruitmentSource      0
Absences              31
dtype: int64

In [53]:
# Additional data analysis of my choice
#calculating the correlation matrix
df.corr()

<ipython-input-53-727d6807764c>:3: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.corr()

               EmpID    Salary  PositionID  ManagerID  Absences
EmpID       1.000000 -0.121375   -0.036488   0.090236 -0.026915
Salary     -0.121375  1.000000   -0.141389  -0.473396  0.109548
PositionID -0.036488 -0.141389    1.000000   0.098005 -0.087261
ManagerID   0.090236 -0.473396    0.098005   1.000000  0.115560
Absences   -0.026915  0.109548   -0.087261   0.115560  1.000000

In [54]:
# calculating the average Salary of employees by department
average_age_by_department = df.groupby('Department')['Salary'].mean()
print("\nAverage age by department:\n", average_age_by_department)

Average age by department:
 Department
Admin Offices           69135.125000
Executive Office                 NaN
IT/IS                   97054.222222
Production              59914.532544
Sales                   69273.692308
Software Engineering    95148.800000
Name: Salary, dtype: float64

### Do the following steps for each column with missing values.

* Identity the column
* How much precentage the missing value represents
* What is the best way to handle these missing values and why
* Apply your method to the column

In [55]:
#Identity the column

columns_with_missing_values = df.columns[df.isnull().any()]
print("Columns with missing values:")
print(columns_with_missing_values)

Columns with missing values:
Index(['Employee_Name', 'Salary', 'DOB', 'Sex', 'DateofTermination',
       'ManagerID', 'Absences'],
      dtype='object')

In [56]:
#How much precentage the missing value represents
missing_percentage = (df.isnull().sum() / len(df)) * 100
print("Missing value percentages:")
print(missing_percentage)

Missing value percentages:
Employee_Name        29.903537
EmpID                 0.000000
Salary               19.935691
PositionID            0.000000
Position              0.000000
DOB                   9.967846
Sex                  19.935691
MaritalDesc           0.000000
RaceDesc              0.000000
DateofHire            0.000000
DateofTermination    66.559486
Department            0.000000
ManagerName           0.000000
ManagerID             2.572347
RecruitmentSource     0.000000
Absences              9.967846
dtype: float64

In [57]:
# Calculate the overall sum of the percentages of missing values
overall_missing_percentage = missing_percentage.sum()

print("Overall sum of missing value percentages:", overall_missing_percentage)

Overall sum of missing value percentages: 158.84244372990355

###Since it's a categorical column representing the names of employees. Instead of dropping or imputing values, one option is to assign a placeholder value such as Unknown

In [61]:
# Replace missing values with "Unknown"
df['Employee_Name'].fillna("Unknown", inplace=True)

# Print the updated column with missing values handled
print("Data with missing values handled in 'Employee_Name' column:")
df['Employee_Name']

Data with missing values handled in 'Employee_Name' column:

0           Adinolfi, Wilson  K
1      Ait Sidi, Karthikeyan
2             Akinkuolie, Sarah
3                  Alagbe,Trina
4                       Unknown
                 ...
306              Woodson, Jason
307          Ybarra, Catherine
308                     Unknown
309                 Zhou, Julia
310                     Unknown
Name: Employee_Name, Length: 311, dtype: object

###Since It's a numerical column the best way is  Imputation with Mean/Median: One approach is to impute the missing values with the mean or median of the 'Salary' column. This method assumes that the missing values are missing at random and that the distribution of salaries is approximately normal.

In [63]:
# Calculate the mean or median of the 'Salary' column
mean_salary = df['Salary'].mean()
#OR median_salary = df['Salary'].median()

# Impute missing values with the mean or median
df['Salary'].fillna(mean_salary, inplace=True)
df['Salary']

0       62506.0
1      104437.0
2       64955.0
3       64991.0
4       50825.0
         ...
306     65893.0
307     48513.0
308    220450.0
309     89292.0
310     45046.0
Name: Salary, Length: 311, dtype: float64

### Since It's Date of Birth I was confused, but I applied two methods First is Imputation with Mean/Median: One approach is to impute the missing values with the mean or median of the available dates of birth. However, imputing dates may not be appropriate in all cases, especially if the missing values are not missing at random. Second is Create a Missing Indicator: Instead of imputing the missing values, you can create a separate column that indicates whether the 'DOB' value was missing or not. This approach allows you to retain the information that a value was missing without distorting the distribution of dates of birth because sometime we can not We predict a person's date of birth

In [67]:
# Calculate the mode of the 'DOB' column
mode_dob = df['DOB'].mode()[0]

# Impute missing values with the mode
df['DOB'].fillna(mode_dob, inplace=True)
df['DOB']

#____________________OR___________________________

#  Create a missing indicator column
df['DOB_Missing'] = df['DOB'].isnull().astype(int)
df['DOB']

0      07/10/83
1      05/05/75
2      09/19/88
3      06/14/87
4      09/08/89
         ...
306    05/11/85
307    06/14/87
308    06/14/87
309    02/24/79
310    08/17/78
Name: DOB, Length: 311, dtype: object

### Since It's sex I was confused, but I applied two methods Mode Imputation: If the missing values in the 'Sex' column are relatively few, you can impute them with the mode (the most frequent value) of the 'Sex' column. This assumes that the missing values are missing at random and that the mode represents a reasonable estimate for the missing values.or we Create a Missing Indicator: Instead of imputing the missing values, you can create a separate column that indicates whether the 'Sex' value was missing or not. This approach allows you to retain the information that a value was missing without distorting the distribution of the existing categories.

In [68]:
# Calculate the mode of the 'Sex' column
mode_sex = df['Sex'].mode()[0]

# Impute missing values with the mode
df['Sex'].fillna(mode_sex, inplace=True)
df['Sex']

#____________________OR___________________________


# Create a missing indicator column
df['Sex_Missing'] = df['Sex'].isnull().astype(int)

0      M
1      M
2       F
3       F
4       F
       ..
306    M
307     F
308     F
309     F
310     F
Name: Sex, Length: 311, dtype: object

### Since It's DateofTermination I was confused, but I applied two methods Imputation with a Specific Value: If the missing values in the 'DateofTermination' column indicate that the employee has not been terminated, you can impute the missing values with a specific value, such as 'Still Employed' or 'N/A'. or Create a Termination Indicator: Instead of imputing the missing values, you can create a separate column that indicates whether the employee has been terminated or not. This approach allows you to retain the information that a termination date was missing without distorting the distribution of termination dates.

In [70]:

# Impute missing values with a specific value
df['DateofTermination'].fillna('Still Employed', inplace=True)


#____________________OR___________________________

# Create a termination indicator column
df['Terminated'] = df['DateofTermination'].notnull().astype(int)

### Since It's managerID I was confused, but I applied two methods Imputation with a Specific Value: If the missing values in the 'ManagerID' column represent a specific category (e.g., no manager assigned), you can impute the missing values with a specific value, such as 'No Manager' or 'N/A'. or Imputation with Mode: If the missing values in the 'ManagerID' column are relatively few and there is a dominant 'ManagerID' value (mode), you can impute the missing values with the mode of the 'ManagerID' column.

In [71]:
# Impute missing values with a specific value
df['ManagerID'].fillna('No Manager', inplace=True)


#____________________OR___________________________


# Calculate the mode of the 'ManagerID' column
mode_manager_id = df['ManagerID'].mode()[0]

# Impute missing values with the mode
df['ManagerID'].fillna(mode_manager_id, inplace=True)

### Since it's Absences the best way it's Imputation with Mean/Median: One approach is to impute the missing values with the mean or median of the available 'Absences' values. This method assumes that the missing values are missing at random and that the distribution of absences is relatively normal.

In [72]:
# Calculate the mean or median of the 'Absences' column
mean_absences = df['Absences'].mean()
# median_absences = df['Absences'].median()

# Impute missing values with the mean or median
df['Absences'].fillna(mean_absences, inplace=True)

In [73]:
df.isnull().sum()

Employee_Name        0
EmpID                0
Salary               0
PositionID           0
Position             0
DOB                  0
Sex                  0
MaritalDesc          0
RaceDesc             0
DateofHire           0
DateofTermination    0
Department           0
ManagerName          0
ManagerID            0
RecruitmentSource    0
Absences             0
DOB_Missing          0
Terminated           0
dtype: int64